---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksdemo-eksctl
  region: ap-southeast-1

managedNodeGroups:
- name: eksdemo-nodegroup
  instanceType: t3.medium
  desiredCapacity: 1
  minSize: 1
  maxSize: 3
  iam:
    withAddonPolicies:
      albIngress: true
      cloudWatch: true
      autoScaler: true

cloudWatch:
  clusterLogging:
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"
    enableTypes: ["*"]
